version: '3'
services:
  web:
    build: .
    container_name: "traning-docker"
    volumes:
      - www:/training-docker/dist
  nginx-proxy:
    image: nginx
    container_name: "training-nginx"
    ports:
      - "8080:8080"
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d:ro
      - www:/www:ro
volumes:
  www:
